sudo: required
services: docker
env:
  - REPOSITORY=stevemcgrath/nessus_scanner IMAGE_NAME=nessus_scanner
script: 
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - docker build . -t ${IMAGE_NAME}:latest
  - version=$(docker run --rm -it ${IMAGE_NAME}:latest /opt/nessus/sbin/nessusd --version | awk '{print $3}' | head -n1)
  - major=$(echo ${version} | cut -d '.' -f 1)
  - minor=$(echo ${version} | cut -d '.' -f 2)
  - docker tag nessus:latest ${REPOSITORY}:${major}
  - docker tag ${IMAGE_NAME}:latest ${REPOSITORY}:${major}.${minor}
  - docker tag ${IMAGE_NAME}:latest ${REPOSITORY}:latest
  - docker push ${REPOSITORY}:${major}
  - docker push ${REPOSITORY}:${major}.${minor}
  - docker push ${REPOSITORY}:latest