sudo: required
services: docker
before_install: sudo pip install csup
script: 
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - docker build . -t nessus_scanner:latest
  - csup upload nessus_scanner --tag latest --consec-name sensors/nessus --consec-tag latest -rp
  - export VERSION=$(docker run --rm -it nessus_scanner:latest /opt/nessus/sbin/nessusd --version | awk '{print $3}' | head -n1)
  - export MAJOR=$(echo ${VERSION} | cut -d '.' -f 1)
  - export MINOR=$(echo ${VERSION} | cut -d '.' -f 2)
  - echo "Discovered Nessus Version ${VERSION} - ${MAJOR}.${MINOR}"
  - docker tag nessus_scanner:latest stevemcgrath/nessus_scanner:${MAJOR}
  - docker tag nessus_scanner:latest stevemcgrath/nessus_scanner:${MAJOR}.${MINOR}
  - docker tag nessus_scanner:latest stevemcgrath/nessus_scanner:latest
  - docker push stevemcgrath/nessus_scanner:${MAJOR}
  - docker push stevemcgrath/nessus_scanner:${MAJOR}.${MINOR}
  - docker push stevemcgrath/nessus_scanner:latest